### ISSUE TITLE
The PyPI release is broken

### ISSUE THREAD

**Issue by orsinium** [ikvk/pdf417as_str#2]
1. Download the distribution file: https://files.pythonhosted.org/packages/26/18/b0bb1c7cd285a3411885de815b5ed470ab4a025580303e12c9040ee32b53/pdf417as-str-1.0.0.tar.gz
2. Open `/pdf417as-str-1.0.0/pdf417as_str/__init__.py` 
3. The content of the file is `from .main import encode`. It should be `from .main import encode417`.

The code in the repo is correct. Just uploading a new release should solve the problem.

**Comment by ikvk** [comment]
thx

**Comment by ikvk** [comment]
check it https://github.com/ikvk/pdf417as_str/releases/tag/v1.1.0
